### PR TITLE
Add standalone test for drakevisualizer

### PR DESCRIPTION
**Pull request by rdeits**
These commits got lost when #275 was closed. 

This adds a simple standalone python script to demonstrate interacting with the `drake-visualizer` application.

### CODE REVIEW

**Comment by rdeits** [comment]
(note that getting CI results back today will be slower than usual due to issues with Travis OSX VMs: https://www.traviscistatus.com/incidents/nq0sf0srvx8s)

**Comment by patmarion** [comment]
great to have this new test, but why all the extra cmake code to run it with 'standalone' python interp?

**Comment by rdeits** [comment]
Uh, I swear there was a reason when I did this back in June, but I can't remember what it was. I'll try getting rid of it to figure out why it's there.

**Comment by patmarion** [comment]
btw, if you run the script with directorPython, you could use that path (sys.argv[0]) to find drake-visualizer.  i see in your cmake code you set the PATH environment variable as another way

**Comment by rdeits** [comment]
Ok, I've removed the standalone cmake logic and used sys.argv[0] to find the drake-visualizer command. Let's see if that works.

**Comment by rdeits** [comment]
@patmarion is investigating why `sys.argv[0]` isn't set in `directorPython`

**Pull request merged**
