### PR TITLE
Shiny new drake visualizer

### LINKED ISSUE #415: New drake visualizer interface
Continuing the discussion from https://github.com/rdeits/DrakeVisualizer.jl/issues/21#issuecomment-268728737

I'd like to propose a complete overhaul of the drake visualizer interface. The current drake-visualizer is great, but it has several issues that can't be avoided with its current architecture:

* clients must always send a LOAD message before sending a DRAW message. If the visualizer is ever restarted, the clients have no way of knowing, and will just keep sending useless DRAW messages. 
* the only organizational structure allowed is an integer robot_id_number and a string link name
* the only way to add new geometries or add new features to existing geometries is to pack floats into the float_data of the `viewer_geometry_data_t` lcmtype, which is extremely clunky
* drake-visualizer currently uses entirely different channels and code paths to draw
  * link geometries
  * lidar points
  * pointclouds
* that means that, for example, several lidars cannot be rigidly connected, and a pointcloud cannot be attached to a robot link

To solve all of these issues, I'm proposing several major changes:

* Create a response protocol for the visualizer, which at least indicates whether a given action (like DRAW or LOAD) was successful. 
  * More specifically, when a client tries to draw a link at a given pose, the visualizer may respond with a "no such link" message and the name of that link, so that the client can send an appropriate LOAD message
* Stop using LCM types for geometry data. The fact that new fields cannot be added to LCM types without breaking compatibility is a major annoyance. Instead, we can just pack a set of bytes that encode, e.g. a JSON string into an LCM message. This makes it trivial to add new options in the future, without breaking compatibility
* Use this increased type flexibility to make pointclouds and lidars just another geometry type. This makes it easy to add pointclouds which rigidly move together (by attaching them to the same link)
* Replace the "robot_id_num" and link name concepts with a general "path" concept. A path is a list of strings, and a link with path ["robot1", "group2", "link3"] is placed in the folder `robot1/group2/link3` in the visualizer. This reproduces all of the capability of the robot_id_num concept and also allows lots of other organizational schemes

I've done all of the above on my branch here: https://github.com/rdeits/director/tree/json-interface

Pointclouds, meshes, LIDARs, and geometric primitives are all working. The basic client-server protocol is working, so now the visualizer can be killed and restarted while a client is drawing, and everything will "just work" (i.e. the model will be re-loaded when necessary). It also makes most of the drake visualizer code quite a bit simpler, since we don't have separate code for pointclouds and lidars. 

It's possible to use the new interface without the client being smart: if you just blindly send LOAD and then DRAW (the way the clients do now), everything will work. You just won't have the benefit of being able to stop and start the viewer at will. 

But before I PR this, I want to make sure this is the right thing to do. I don't imagine we'll want to delete the current drake-visualizer. Instead, I think we should keep it (but deprecate it) and bring in the new interface as `drake-visualizer2` or similar. 

Also, I haven't noticed any performance issues from the switch from LCM types to JSON dicts. But if there is one, we can trivially swap out JSON for MsgPack with almost no code change (and we can support clients using both formats with no trouble).

### PR DESCRIPTION
**Pull request by rdeits**
Copied from #419 so @patmarion can also push to the branch. 

@patmarion this will probably need some work before it's ready to merge, but I wanted to get started on the PR now. 

This implements the interface described in #415 (closes #415)

I've split the old `drakevisualizer.py` into `drakevisualizer.py` and `drakevisualizerapp.py`. I've also created the new interface in `drakevisualizer2.py`. Additionally, I've created `drakevisualizerapp1.py` and `drakevisualizerapp2.py` which import the relevant modules to construct the v1 and v2 apps. And I've added a command line flag to `drakeVisualizerApp.cpp`

@patmarion I have no attachment to any of those naming choices. They're just the first thing I tried that managed to cleanly separate all the old and new functionality. Feel free to rearrange and rename them as you see fit. Everything I've added is contained in `drakevisualizer2.py` and the new `testDrakeVisualizer2Interface.py`; all the other changes are just rearrangements of existing code.

### CODE REVIEW

**Comment by rdeits** [comment]
@patmarion I added one commit to support the optional "transform" attribute for geometries: 972a6ee

**Comment by rdeits** [comment]
@patmarion FYI I pushed one more commit to remove some duplication from the status messages

**Comment by rdeits** [comment]
@patmarion so far, performance is OK with this change, but not great. The biggest slowdown turns out not to be JSON-related, but just due to searching through the objectmodel. When a client sends something like `draw path ["foo", "bar", "baz"] at transform T`, director has to search through the objectmodel for folder foo, then for its child bar, then for its child baz. This turns out to be surprisingly slow (about 300 microseconds per robot link), especially for complicated robots. Is there any way for me to access folders in the objectmodel more quickly than just doing a bunch of `findChild` calls? 

If I have to cache these lookups I will, but I'd really rather avoid introducing all of the obvious problems that caching always creates.

**Comment by patmarion** [comment]
The object model cannot provide speedy name lookups because:

  - item names do not have to be unique
  - item names may be changed at any time

However, the rules of the drawing protocol say that names are unique (since it is path based) so I would recommend that the drawing class caches the items in a python dict by pathname, then let's discuss where that could be buggy.

**Comment by rdeits** [comment]
Ok, sounds good. The particular issue I ran into when I tried that was that it's easy to keep a cache inside the `DrakeVisualizer` class and remove elements when the client sends a `delete` message. But we also have to ensure that the cache is cleared when the user does something like manually delete a folder from the objectmodel in director.

**Comment by patmarion** [comment]
There is a callback you can use whenever an item is removed from the object model.  It is fired exactly once as the item is removed.  Triggered for each item whether an item is removed programmatically or by the user pressing 'delete' on an item or folder.

```

def onItemRemoved(self, objModel, item):
    # remove item from cache

def addItem(path, item):
  self.cache[path] = item
  item.connectRemovedFromObjectModel(self.onItemRemoved)

```

**Comment by rdeits** [comment]
Ok, thanks, that's perfect.

**Comment by rdeits** [comment]
@patmarion I'm making the minor changes to the way format versions are specified that we talked about today. Also, we should remember to deal with the new LCM type that I added to bot core (this PR currently points Director's build to my fork of bot core types)

**Comment by rdeits** [comment]
Also, I'm using the `viewer2` name in a few places in code to refer to this version of the visualizer. If we want to give it a better name, now would be a good time.

**Pull request merged**
