### PR TITLE
Update to python3

### PR DESCRIPTION
**Pull request by patmarion**
work in progress to get travisci green.  this commit is based on the python3 branch

### CODE REVIEW

**Comment by patmarion** [comment]
This PR includes updates to support:

 - python3 (python2 dropped)
 - vtk 8.2
 - ubuntu 16.04 and 18.04 (14.04 dropped)
 - latest homebrew on mac mojave

**Comment by EricCousineau-TRI** [comment]
This looks awesome! Can I ask if you have an idea of when we might be able to merge this? Is there anything we can help with?

**Comment by patmarion** [comment]
Hi Eric, I am prepared to merge this now.  Does that work for the drake users?

**Comment by EricCousineau-TRI** [comment]
Yes, that would be excellent for us - thank you!

**Comment by patmarion** [comment]
Ok, `master` is now using python3.  I pushed a branch named `py2-support` which is a snapshot of the previous `master` so folks can still use that if they need python 2.

Eric, please let me know if you get a chance to try the new python3 `master` branch and let me know if you find any bugs, thanks!

**Comment by EricCousineau-TRI** [comment]
Awesome, thank you so much!

**Pull request merged**
