### PR TITLE
update director to new drake

### PR DESCRIPTION
**Pull request by mauricefallon**
Pairs with https://github.com/mitdrc/drc/pull/2142/files

Currently this compiles but fails at run time. 
The major problem is that KinematicsCache separates the result of doKinematics() from the RBM.
I couldn't resolve how to pass the cache around with RBM object.

These two methods have problems:
URDFRigidBodyManipulatorVTK::getLinkToWorld
ddDrakeWrapper::resolveCenterOfPressure

### CODE REVIEW

**Comment by mauricefallon** [comment]
@patmarion : feel free to rewrite this PR. I'm not happy with it and it does work at run time.

**Comment by patmarion** [comment]
I got the drake-designer to compile and load correctly.  Next up, we have to fix the matlab code in the IK server.  Besides the new KinectmaticsCache, there was also a change to coordinate frame access.  This is the first error message printed when starting the IK matlab server:

    You cannot get the 'coordinates' property of 'CoordinateFrame'.

    Error in IKServer/addRobot (line 142)
          obj.plan_publisher = RobotPlanPublisherWKeyFrames('CANDIDATE_MANIP_PLAN',
          true, obj.robot.getPositionFrame.coordinates);

**Comment by patmarion** [comment]
I also found a strange import error when importing iris.  I was able to work around the error by importing iris before any other module.  The error was:

  File "/home/pat/source/drc/drc/software/build/lib/python2.7/dist-packages/ddapp/irisUtils.py", line 4, in <module>
    from irispy.utils import lcon_to_vert
  File "/home/pat/source/drc/drc/software/build/lib/python2.7/dist-packages/irispy/__init__.py", line 1, in <module>
    from irispy import Polyhedron, Ellipsoid, IRISRegion, IRISOptions, IRISProblem, inflate_region, c_inflate_region
  File "/home/pat/source/drc/drc/software/build/lib/python2.7/dist-packages/irispy/irispy.py", line 1, in <module>
    from iris_wrapper import IRISOptions, IRISRegion, IRISProblem, IRISDebugData, Ellipsoid, Polyhedron
  File "/home/pat/source/drc/drc/software/build/lib/python2.7/dist-packages/irispy/iris_wrapper.py", line 28, in <module>
    _iris_wrapper = swig_import_helper()
  File "/home/pat/source/drc/drc/software/build/lib/python2.7/dist-packages/irispy/iris_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_iris_wrapper', fp, pathname, description)
ImportError: dlopen: cannot load any more object with static TLS

**Comment by patmarion** [comment]
I updated the drc branch to point to my new commits here, btw.  I force pushed over your branch mitdrc/mfallon-update-drake

**Comment by mauricefallon** [comment]
coordinates has been made private in the CoordinateFrame class.
You can use getCoordinateNames()

**Comment by patmarion** [comment]
Note, there is also a potential bug in the generation of drake lcmtypes.  If you use lcm v1.0, you won't have the bug.  But I do have the bug in lcm 1.2.  I have reported it here, with a work around:

https://github.com/RobotLocomotion/drake/issues/1425

**Comment by mauricefallon** [comment]
Do you want to had this back to me to look at the IK server?

**Comment by patmarion** [comment]
Pushed new commits.  I made fixes to the coordinates api and now the matlab code is running.  I tested IK planning in the director, footstep and walk planning, and ran the walking simulation in simul_v5.pmd.

I did not go through all matlab files in src/control to fix the coordinate names api change, I only touched the files we used while running Atlas.

I have not tested that matlab code in the collision free planner yet.

**Comment by mauricefallon** [comment]
Great! I checked the collision free planning code before running the test scripts in src/matlab
what's left to check?

**Comment by patmarion** [comment]
Happy to merge now and fix things as they are discovered.

**Pull request merged**
