### PR TITLE
Fix OSX build by switching homebrew taps for vtk5

### PR DESCRIPTION
**Pull request by rdeits**
homebrew/science doesn't include vtk5 anymore, so we have to work around it.

### CODE REVIEW

**Comment by rdeits** [comment]
Sweet. This works. I had to update the bottle to internally point to my vtk5 tap, but it was otherwise pretty easy.

**Comment by rdeits** [comment]
Ok, I think this is ready to go. We may want to change the tap again once https://github.com/RobotLocomotion/homebrew-director comes online. 

Can I get a review?

**Comment by mauricefallon** [comment]
i can't review this as I don't use OSX

**Comment by wxmerkt** [comment]
LGTM. Thanks for fixing this! Would you mind updating the README as well? :)

**Comment by wxmerkt** [comment]
Two more things:
- RL/homebrew-director is now online - should we change this here to use it?
- [for future] The vtk bottle should perhaps be put on a server different from Dropbox. Dropbox blocks links if there's too much traffic (unlikely), sometimes has random timeouts, and in general slows the connection down for public links

**Comment by rdeits** [comment]
Ok, I've switched to robotlocomotion/director and updated the readme. And agreed that dropbox is not a great solution for the future :)

**Pull request merged**
