### PR TITLE
Point cv-utils to a version compatible with libbot as installed by modern Drake

### PR DESCRIPTION
**Pull request by gizatt**
(Remove references to the C libbot LCM types.)

### CODE REVIEW

**Comment by gizatt** [comment]
@manuelli

**Comment by manuelli** [comment]
LGTM

**Comment by manuelli** [comment]
It looks like the build and tests are passing, but problems when uploading the results via http? @patmarion 

```
 Error when uploading file: /home/travis/build/RobotLocomotion/director/build/src/director-build/Testing/20180125-2147/Build.xml
   Error message was: Failed to connect to 128.30.27.135 port 80: Connection timed out
   Problems when submitting via HTTP
```

**Comment by patmarion** [comment]
Yes, it's been broken for that reason for a little while.  I need to locate a new server.

Please go ahead and merge.

**Comment by manuelli** [comment]
@patmarion I don't have merge permissions

**Pull request merged**
