### PR TITLE
Displaying stereo cloud with limited depth

### PR DESCRIPTION
**Pull request by raluca-scona**
Added capability to display stereo cloud within a set depth. Default range is -1, which does not do any filtering.

### CODE REVIEW

**Comment by mauricefallon** [comment]
Have you done evaluation into how quick this is - compared to not carrying out this filter?

It is possible to apply the threshold in the original conversion library:
https://github.com/openhumanoids/cv_utils/blob/master/multisense_utils/src/multisense_utils/multisense_utils.cpp#L76
This is already doing a loop over the point cloud and accessing the z value so could be much quicker.

**Comment by raluca-scona** [comment]
Hi,

This filter requires around 7ms to run, so it 'feels' real-time. I made a video of what this looks like:

https://www.dropbox.com/s/5xr63kwax1inxpe/demo-depth-filter.mkv?dl=0

I am scrolling through the Max Range parameter in the bottom left corner.

**Comment by patmarion** [comment]
This PR sets up the plumbing to get the max range parameter exposed to the user, very nice.  Agreed that it could probably be faster if the range parameter is passed into the multisense_utils library.  Since it's fast enough for now, I'm happy to accept this PR and we can always speed it up down the road if needed.  Maybe it is fast enough anyway because the parameter reduces the point cloud size.

The ddBotImageQueue class does need some threading to really make it feel snappy.  Right now the image conversion and stereo point cloud conversion both slow down the GUI unnecessarily because it happens on the main thread.  This has been on my todo list forever but has not yet been a priority.

**Comment by mauricefallon** [comment]
I agree. Thanks for the video @raluca-scona . The video is compelling and the computation doesn't seem to be too much.

**Comment by patmarion** [comment]
In order to get this into oh-distro we need to verify director master still works with exotica @VladimirIvan thanks!

**Pull request merged**
