### PR TITLE
Update bot image queue for pointcloud visualization

### PR DESCRIPTION
**Pull request by gizatt**
- Enables build of bot_image_queue
- Disables kinectLCM driver
- Updates cameraview.py to be compatible with VTK \geq 6

Submitting so testing can spin up, but I'm happy to add a build option to allow this bit of code to only build when requested, since it has a more involved dependency list.

### CODE REVIEW

**Comment by gizatt** [comment]
Tweaked to build the new stuff only when the dependencies are available

**Comment by peteflorence** [comment]
We should test this on VTK 6/7 before merging (so far only tested on VTK 8)

**Comment by patmarion** [comment]
I can merge all the changes except the changes to the CMakeLists.txt.  For the CMakeLists.txt, I'd like to introduce the option "USE_PERCEPTION" which enables the search for opencv, pcl, and cv-utils and adds ddBotImageQueue to the build.  I would also keep the USE_DRC option in case there are still some openhumanoids specific requirements.

In general I like to be explicit, by having options like USE_PERCEPTION, rather than searching for PCL and if it is found then automatically enabling files.  Because then you can't turn things off except by uninstalling PCL.

**Comment by patmarion** [comment]
> We should test this on VTK 6/7 before merging (so far only tested on VTK 8)

Thanks for the suggestions.  I think the vtk api changes look reasonable to me and are likely to work on vtk7.

**Comment by gizatt** [comment]
Thanks for the suggestion, switched to a USE_PERCEPTION flag. Did I put that option everywhere I ought to?

**Comment by patmarion** [comment]
LGTM!  Thanks.  I will wait for Travis-CI to post the results and then merge.

**Pull request merged**
