### PR TITLE
Allow to manually set CMAKE_INSTALL_RPATH for packaging on MacOS

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by patmarion** [comment]
the mac build failed, but seemingly for an unrelated reason.  i just restarted it to try again.

this diff looks good to me, but i'll need to test it since it may change a few defaults, can't quite tell.  in case you didn't know, Director has it's own mac packaging script which has been quite stable for a long time.  I understand you are making these diffs to enable external packaging, but I just need to make sure it does not break the existing mac packaging.

**Comment by patmarion** [comment]
lgtm, want to update for openni2 camera driver?

**Comment by patmarion** [comment]
note, travis-ci only builds the mac packages for the master branch, it does not build and upload packages on PRs.  So after this is merged to master I will grab the mac package and verify it's still good.

**Comment by fbudin69500** [comment]
@patmarion Thanks for checking that this PR is not breaking anything. I have to make I think 2 more PRs before I can update this one: PointCloudLibraryPlugin (which is your project so that should be easy), and AprilTags (I don't know if you have any control over that project, both to update INSTALL_NAME_DIR setting.

**Comment by fbudin69500** [comment]
Actually my PR for ApriTags has already been merged:
https://github.com/psiorx/apriltags-pod/pull/1
And I just created the PR for PointCloudLibraryPlugin:
https://github.com/patmarion/PointCloudLibraryPlugin/pull/3

**Comment by patmarion** [comment]
sorry i somehow missed your recent updates.  im gonna merge this now and verify it's ok, and you can open a new PR to get the last few projects.

**Comment by patmarion** [comment]
Just tested the latest mac package built on Travis-CI and uploaded to Bintray.  Works as expected.  Thanks!

https://bintray.com/patmarion/director/director/0.1.0-234-g74cea84#files

**Comment by fbudin69500** [comment]
@patmarion I created a new PR to update PointCloudLibraryPlugin in director:
https://github.com/RobotLocomotion/director/pull/560

**Pull request merged**
