### PR TITLE
Update cv-utils git tag and pass more cmake flags down to external projects

### PR DESCRIPTION
**Pull request by jamiesnape**
PTAL @patmarion.

### CODE REVIEW

**Comment by patmarion** [comment]
Just curious, what's the use case for the new cmake flags?

**Comment by jamiesnape** [comment]
CCache mostly.

**Comment by patmarion** [comment]
Do users set all these flags on the command line?

**Comment by jamiesnape** [comment]
The `CMAKE_<LANG>_COMPILER_LAUNCHER` variables are the most relevant one, and you would set them to the location of CCache or to a launcher script.

**Pull request merged**
