### PR TITLE
Updates to use includes from drake/multibody

### PR DESCRIPTION
**Pull request by amcastro-tri**
This PR simply refactors the RBT related include files as suggested by @patmarion in #363.

@patmarion, could you review this please?

### CODE REVIEW

**Comment by patmarion** [comment]
Looks good!

Do you know how to use git submodules to set your drake branch to use your director branch amcastro-tri/move_RBT for CI testing?  That way, instead of merging this PR early, we can delay it until the drake PR is reviewed and passes tests.

**Comment by amcastro-tri** [comment]
I do that for testing locally. I dont think anybody will like the idea of my Drake PR branch pointing to my fork of Director for Drake CI.
What I was thinking was this:
1. Test local compilation/tests with my branch of director.
2. Merge this PR changes for Director (Still Drake would be pointing to 56b8fd7 without these changes).
3. Merge Drake's PR RobotLocomotion/drake#4058 (with the dummy files I added we don't even need to coordinate with Director's merge).
4. New PR in Drake that removes dummy files and changes the hash for Director to point to the most up to date master.

What do you think? The idea is (as we did with the `RBT<T>` PR) to be able to push small updates to Drake and Director without having to coordinate these PR's and most importantly without running the risk of breaking any of their master branches in the process.

cc'ing @jwnimmer-tri

**Comment by patmarion** [comment]
I don't see the problem with changing the submodule reference for testing on CI.  Obviously you would not merge it like that.  Once the builds and tests are passing on CI and your code is reviewed, then I'll merge the director branch, you update the submodule reference, and merge your drake branch.

You can use the dummy files for this drake PR, that's fine, I get what you are saying, but my point is that in general you won't always be able to make your changes in small steps like that, so I was just suggesting a processes that avoids all the extra PRs while still being pretty atomic.

**Comment by jwnimmer-tri** [comment]
FWIW -- speaking as Drake platform reviewer, I am fine with the idea of a Drake PR's Director sha pointing off-master, and then repointing it to Director master before merging the Drake PR.  We just have to be very careful to not screw it up and ever have a non-master sha on drake master.

Whether that tactic should be used, vs deprecation shims, vs any other technique, I will leave up to the PR author and specific circumstances.

**Comment by amcastro-tri** [comment]
Oh, I see what you are saying now @patmarion. My bad, I thought you were suggestion merging the Drake PR pointing to my personal fork of Director. In that case I actually like that idea. I will go ahead and try that.
Thanks @patmarion and @jwnimmer-tri for the feedback!

**Comment by patmarion** [comment]
Ok.  Anyway, this PR looks good and I'll merge it when the drake PR is ready.  Or if you do decide to use the dummy files and merge your drake PR first, that's totally fine by me, but you'll then need a follow up drake PR.  Either way, ping me when ready, thanks!

**Comment by amcastro-tri** [comment]
@patmarion, RobotLocomotion/drake#4058 passed CI. Therefore I think we are ready to merge this PR if you agree.

**Comment by jwnimmer-tri** [comment]
So 4058 is going to take at least another day before merge.  Why not hold off the director merge until Drake's review and fixes are almost complete?

**Comment by amcastro-tri** [comment]
I actually see no reason why to hold off since in any case it would not break anything. The "Director part" ofr 4058 has been stable for more than a day. Today most of the work was mostly getting the paths to urdf/sdf files right for unit tests in Matlab. Also resolving conflicts takes a lot of work and that's why the urgency to merge.

**Comment by patmarion** [comment]
There won't be conflicts on this PR, it's safe to leave it pending for now.  (If there are I'll resolve them)

I'll wait until drake 4058 gets the LGTM from reviewers and then merge this one.

**Comment by amcastro-tri** [comment]
SGTM, thanks.

**Comment by amcastro-tri** [comment]
@patmarion, we are ready to test this with RobotLocomotion/drake#4058 since CI has been passing. Now we are just in the process of fixing the latest conflicts with new PR's that arrived.
Would you be able to merge please?

**Pull request merged**
