### PR TITLE
switch back to just `drake` as lcmtypes package name

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by patmarion** [comment]
@rdeits would you mind rebasing this commit onto director commit 6286695 ?  Thanks!

(drake doesn't track the master branch of director, instead it is set to a branch at the above commit)

**Comment by rdeits** [comment]
done!

**Comment by patmarion** [comment]
Great thanks.  Now you can set the director tag in drake's cmakelists to your commit.

**Comment by rdeits** [comment]
yup, done

**Pull request merged**
