### PR TITLE
continuous walking with val

### PR DESCRIPTION
**Pull request by mauricefallon**
Adds Neck pitch control with Val:
https://www.dropbox.com/s/2ika0icuqlzj7a6/2015-09-neck-control-val.ogv?dl=0

Also adds a few minor changes towards continuous walking in Val:
https://www.dropbox.com/s/oenqu0523ffvdul/2015-09-continuous-walking.ogv?dl=0
@patmarion @rdeits  all the footstep planning and perception code from Dec 2014 still works ;)

### CODE REVIEW

**Comment by patmarion** [comment]
@mauricefallon I have new work in progress code for continuous walking, but it may be some time before I can merge it (paper, wedding :)  I'm working on some new terrain perception, using updated segmentation code from the DRC finals and handling ground regions.

**Comment by patmarion** [comment]
nice video!

**Comment by rdeits** [comment]
Awesome!

**Comment by RussTedrake** [comment]
agreed.  very nice!

**Pull request merged**
