### PR TITLE
use new lcmtypes package

### PR DESCRIPTION
**Pull request by rdeits**
to support https://github.com/RobotLocomotion/drake/pull/1380

### CODE REVIEW

**Comment by mauricefallon** [comment]
If the director submodule is referenced in drake is this necessary?

**Comment by patmarion** [comment]
@mauricefallon are you asking if the pull request is necessary?  As in, why merge, instead of just referencing the director branch from drake?  I think this pull request is ok, because it has been written to be backward compatible, and will be necessary when DRC eventually updates its own drake submodule reference.

**Comment by patmarion** [comment]
So I think this one is good, +1.  I'll can for more comments and merge a later today.

**Comment by mauricefallon** [comment]
ok, i see, fine by me

**Pull request merged**
