### PR TITLE
Explicitly require Python 2.7 for compatibility with newer CMake

### PR DESCRIPTION
**Pull request by wxmerkt**
I've had to upgrade CMake to 3.5 in order to compile Drake master for some of my work. Afterwards I've noticed that Director failed to compile from a clean build of oh-distro as the new CMake prefers the newer Python if two versions are installed (e.g. 2.7 and 3.4). This will in turn lead to a compilation error as shown below.

This PR can wait; I'd like to get @patmarion's input on the potential downsides of this change when he's back (e.g. we might not want to restrict to Python2).

---------------

```
[ 29%] Building CXX object src/app/CMakeFiles/ddApp.dir/moc_ddPythonQtDecorators.cxx.o
In file included from /usr/include/python3.4m/pytime.h:6:0,
                 from /usr/include/python3.4m/Python.h:65,
                 from /home/wxm/oh-distro/software/build/include/PythonQt/PythonQtPythonInclude.h:93,
                 from /home/wxm/oh-distro/software/build/include/PythonQt/PythonQtInstanceWrapper.h:45,
                 from /home/wxm/oh-distro/software/build/include/PythonQt/PythonQt.h:46,
                 from /home/wxm/oh-distro/software/director/distro/pods/drc/pod-build/src/app/ddPythonQtDecorators.h:6,
                 from /home/wxm/oh-distro/software/director/distro/pods/drc/pod-build/src/app/moc_ddPythonQtDecorators.cxx:9:
/usr/include/python3.4m/object.h:435:18: error: expected unqualified-id before ‘;’ token
     PyType_Slot *slots; /* terminated by slot==0. */
                  ^
make[2]: *** [src/app/CMakeFiles/ddApp.dir/moc_ddPythonQtDecorators.cxx.o] Error 1
make[1]: *** [src/app/CMakeFiles/ddApp.dir/all] Error 2
make: *** [all] Error 2
```

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/director/286)

### CODE REVIEW

**Comment by RussTedrake** [comment]
+ @RobotLocomotion/kitware .  I think they might have discussed this previously, too.

**Comment by billhoffman** [comment]
I would say restrict it to python 2 as python 3 is a whole different thing and director will not work with it.  So, changing the find python in director to only find 2 would be the way to go.  find_package( PythonInterp 2.7 REQUIRED ) should work.

**Comment by wxmerkt** [comment]
Thank you very much, Russ and Bill! 
I've added the explicit 2.7 version to FindNumpy as well. Is this okay and ready to merge @billhoffman?

**Comment by RussTedrake** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/director/286)*

**Pull request merged**
