### PR TITLE
document treeviewer client_id and line type

### PR DESCRIPTION
**Pull request by rdeits**

### CODE REVIEW

**Comment by rdeits** [comment]
@patmarion do the hosted docs need to get re-generated? I don't see these changes at https://openhumanoids.github.io/director/user_guide/tree_viewer_interface.html

**Comment by patmarion** [comment]
The docs are generated automatically by travis and uploaded to my personal Dropbox.  From there I manually sync the docs to github.io, but I haven't run that syncing command recently... because the docs generation is broken on travis:

The error from https://s3.amazonaws.com/archive.travis-ci.org/jobs/221814958/log.txt is:

```
Scanning dependencies of target docs-sphinx-build
Making output directory...
Running Sphinx v1.2.2
loading translations [en]... done
loading pickled environment... not yet created

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

One time i tried to debug this but didn't invest much time to figure it out.  I think the sphinx docs works fine on my own computer, so i could manually generate the docs and sync with github.io.

In the future it would be nice to automate the whole process.

**Comment by rdeits** [comment]
You just need to `pip install sphinx_rtd_theme`. It used to be included with `sphinx` itself, but no longer.

**Comment by patmarion** [comment]
But I already have that line!  That's the mystery.  I'm pretty sure it used to work.

https://github.com/RobotLocomotion/director/blob/master/distro/travis/before_install.sh#L27

**Comment by patmarion** [comment]
From the travis log I linked to, it says:

`Successfully installed sphinx-rtd-theme-0.2.4`

**Comment by rdeits** [comment]
Not sure if it's relevant, but I actually installed `sphinx_rtd_theme` (underscores not dashes).

**Comment by patmarion** [comment]
fyi, docs are synced now- https://openhumanoids.github.io/director/user_guide/tree_viewer_interface.html

**Pull request merged**
