### PR TITLE
Update to python3

### PR DESCRIPTION
**Pull request by patmarion**

### CODE REVIEW

**Comment by patmarion** [comment]
fyi @rdeits I made this fix when updating to python 3:

https://github.com/RobotLocomotion/director/pull/521/commits/e868ccedf1d40a7296311e76248bb010c95f3225

You might consider changing the data field of viewer2_comms_t from bytes to string type:

https://github.com/RobotLocomotion/lcmtypes/blob/master/lcmtypes/viewer2_comms_t.lcm#L16

**Comment by rdeits** [comment]
Ok, thanks!

**Comment by EricCousineau-TRI** [comment]
@patmarion Can I ask if which branch has the most recent Python 3 updates for `director`?

And I can I ask if you've decided on just moving over to Python 3, dropping Python 2 development?

If it helps at all, here's my very brief investigation into looking at what Python 3 + ROS 1 looks like:
https://github.com/RobotLocomotion/drake/issues/10606#issuecomment-513979322 (summary: complicated)

\cc @jamiesnape

**Comment by patmarion** [comment]
Hi Eric, the most recent python3 development branch is:

https://github.com/patmarion/director/tree/update-mac-build

I have a PR for it here:

https://github.com/RobotLocomotion/director/pull/625

And the most recent travis-ci for that PR was all green for ubuntu 16.04, ubuntu 18.04, and mac (xcode 10.2):

https://travis-ci.org/RobotLocomotion/director/builds/552278930


The branch is named "update-mac-build" but that's a bad name, sorry!  The branch contains the python3 upgrade, and fixes the build for ubuntu 18, vtk 8, and latest mac homebrew.

I've been busy with other things and so I haven't proceeded with landing this branch to master.  But I use this branch as my primary working copy.

**Comment by patmarion** [comment]
This is now the latest PR for python3 into director/master:  #625

**Pull request closed without merging**
