### PR TITLE
add color octree minimal

### PR DESCRIPTION
**Pull request by mauricefallon**
Replacing:
https://github.com/RobotLocomotion/director/pull/177

This its possible to use octovis without modification.

But I have a few CMake issues. Could you suggest fixes?
- octovis doesn't install a pkgconfig file
- octovis requires something called QGLViewer - which is used only in one place - to draw an axes.
It is actually part of octomap and provides as FindQGLViewer.cmake
oh-distro/software/externals/octomap/octovis/src/extern/QGLViewer

I'll also PR some associated changes to open-humanoids if you want them

### CODE REVIEW

**Comment by mauricefallon** [comment]
The future direction:
https://www.dropbox.com/s/0gadcjeqadmqb0k/finals-map.mp4?dl=0
(the colors are mostly horrible at present)

**Comment by patmarion** [comment]
very awesome!

I'm happy to help with the cmake code, I might not get to it right away, though, ok to leave this open a little while longer?

**Comment by mauricefallon** [comment]
take as long as you need!

**Comment by patmarion** [comment]
I just pushed a commit onto this branch to cleanup the cmakelists.

I have a commit to octovis that makes it possible to include octovis headers even though qglviewer is not installed.  I opened a pull request upstream here:

https://github.com/OctoMap/octomap/pull/108

In the meantime, we can change the url of our octomap external to point to my commit.  What do you think?

**Comment by mauricefallon** [comment]
Your SHA is probably on top octomap/master ? 
But this change is unlikely to need such testing.

Go ahead and accept both this and the oh-distro PR, we can revert if necessary

Thanks for the CMake clean up!

**Pull request merged**
