### PR TITLE
visualization: Ensure `updateFrame` passes `parent` correctly

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Follow-up from: https://github.com/RobotLocomotion/drake/pull/11134

@patmarion whenever you have the chance? (not urgent)

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/director/621)

### CODE REVIEW

**Comment by patmarion** [comment]
thanks!

I actually have this fixed in my python3 branch, sorry I haven’t ported everything back to master!


https://github.com/patmarion/director/commit/1db8676e2795298d073d7436d35d9c593a7a5075

I’ll try to get this merged back into master.

**Comment by patmarion** [comment]
i also added a "path" api:

https://github.com/patmarion/director/commit/1df09362102f38355f99615e2383a60578d77e4a

which allows code like `obj = om.findObjectByPath('/folder/subfolder/myobj')` which helps ensure you find the correct object if your application doesn't want to use unique object names.

**Comment by EricCousineau-TRI** [comment]
Sounds good - thanks!
Do you want me to file an issue to track that instead?

**Comment by patmarion** [comment]
I landed the PR that has a lot of the new development work from the py3 branch.  This particular issue should be fixed now, so I will close this PR.  Thanks again for tracking the bug and submitting, always appreciate it!

Hope I didn't break anything with my latest PR!  I've been using it a lot, but with python3.  I tried to give it some good testing on `master`, but let me know if you catch something.

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks!

**Pull request closed without merging**
